/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HumanIdentification;

// import HumanIdentification.Human;
import HumanIdentification.HumanId;



public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        // Human human = new Human ();
        HumanId humanId = new HumanId();

        humanId.HumanIdReg();
        
        humanId.speak();
        humanId.eat();
        humanId.drink();
        humanId.cook();


    }
}
