/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Latihan.OOP;

import main.java.Latihan.OOP.BicycleDemo;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        BicycleDemo bicycleDemo = new BicycleDemo ();
        bicycleDemo.BicycleDemoTest();
        

        
    }
}
